(dp1
S'output'
p2
S"<class '_mysql_exceptions.OperationalError'> (1205, 'Lock wait timeout exceeded; try restarting transaction')"
p3
sS'layer'
p4
S'C:\\Eden\\web2py\\applications\\eden\\models\\zzzz_always_run.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n# always running script\n\ntblname = "inv_inv_item"\n\n# load the inv_inv_item table\n# inventory table\ntable = s3db[tblname]\n\n# check if inventory db table\n# has already been created\n# then update all expired items\n# and near expired items\n\nif tblname in db.tables:\n    invtable = db.inv_inv_item\n    \n    query = ((invtable.expiry_date != None) &\n        (invtable.deleted == False))\n    \n    # change to near expired (7)\n    time_near_ex = current.request.now + datetime.timedelta(days=90)\n    \n    task = db(query &\n        (invtable.expiry_date <= time_near_ex) &\n        (invtable.expiry_date > current.request.now))\n        \n    if task.count():\n        task.update(status=7)\n    \n    # change to expired (6)\n    task = db(query &\n        (invtable.expiry_date <= current.request.now))\n        \n    if task.count():\n        task.update(status=6)\n    \n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Eden\\web2py\\gluon\\restricted.py", line 209, in restricted\n    exec ccode in environment\n  File "C:\\Eden\\web2py\\applications\\eden\\models\\zzzz_always_run.py", line 30, in <module>\n    task.update(status=7)\n  File "C:\\Eden\\web2py\\gluon\\dal.py", line 8826, in update\n    ret = db._adapter.update(tablename,self.query,fields)\n  File "C:\\Eden\\web2py\\gluon\\dal.py", line 1356, in update\n    self.execute(sql)\n  File "C:\\Eden\\web2py\\gluon\\dal.py", line 1676, in execute\n    return self.log_execute(*a, **b)\n  File "C:\\Eden\\web2py\\gluon\\dal.py", line 1670, in log_execute\n    ret = self.cursor.execute(*a, **b)\n  File "C:\\Python27\\lib\\site-packages\\MySQLdb\\cursors.py", line 181, in execute\n    self.errorhandler(self, exc, value)\n  File "C:\\Python27\\lib\\site-packages\\MySQLdb\\connections.py", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (1205, \'Lock wait timeout exceeded; try restarting transaction\')\n'
p11
s.